### ISSUE TITLE
metanorma compile fails with sassc error

### ISSUE THREAD

**Issue by archaeogeek** [metanorma/metanorma-docker#119]
Hello, this is my first foray into metanorma and I've hit a problem. I'm running the docker container on Ubuntu 20.04, and am running the following command:

`docker run -it -v "$(pwd)":/metanorma/ -w /metanorma metanorma/mn:latest metanorma compile -t generic -x html myadoc.adoc`

This fails with the following error:
```
Traceback (most recent call last):
        36: from /usr/local/bundle/bin/metanorma:23:in `<main>'
        35: from /usr/local/bundle/bin/metanorma:23:in `load'
        34: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/exe/metanorma:40:in `<top (required)>'
        33: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/exe/metanorma:22:in `block in <top (required)>'
        32: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli.rb:34:in `start'
        31: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        30: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        29: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        28: from /usr/local/bundle/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
        27: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        26: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/command.rb:45:in `compile'
        25: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/command.rb:45:in `each'
        24: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/command.rb:45:in `block in compile'
        23: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/command.rb:210:in `compile_document'
        22: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/compiler.rb:35:in `compile'
        21: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/compiler.rb:30:in `compile'
        20: from /usr/local/bundle/bundler/gems/metanorma-cli-dc3c6c044cf2/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        19: from /usr/local/bundle/gems/metanorma-1.4.1/lib/metanorma/compile.rb:35:in `compile'
        18: from /usr/local/bundle/gems/metanorma-1.4.1/lib/metanorma/compile.rb:206:in `process_extensions'
        17: from /usr/local/bundle/gems/metanorma-1.4.1/lib/metanorma/compile.rb:206:in `each'
        16: from /usr/local/bundle/gems/metanorma-1.4.1/lib/metanorma/compile.rb:225:in `block in process_extensions'
        15: from /usr/local/bundle/gems/metanorma-generic-1.11.0/lib/metanorma/generic/processor.rb:43:in `output'
        14: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/html_convert.rb:26:in `convert'
        13: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/convert.rb:175:in `convert'
        12: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/html_function/html.rb:9:in `convert1'
        11: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/function/utils.rb:33:in `noko'
        10: from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:292:in `with'
         9: from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:292:in `new'
         8: from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:334:in `initialize'
         7: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/html_function/html.rb:10:in `block in convert1'
         6: from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:416:in `method_missing'
         5: from /usr/local/bundle/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
         4: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/html_function/html.rb:12:in `block (2 levels) in convert1'
         3: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/css.rb:28:in `populate_css'
         2: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/css.rb:100:in `generate_css'
         1: from /usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/css.rb:78:in `convert_scss'
/usr/local/bundle/gems/isodoc-1.8.1/lib/isodoc/css.rb:78:in `require': cannot load such file -- sassc (LoadError)
```

However if I run the following instead:
`docker run -it -v "$(pwd)":/metanorma/ -w /metanorma metanorma/mn:latest metanorma compile -t iso -x html myadoc.adoc`
Then the command finishes.

Note that I get the same results regardless of which metanorma container I use.

I'm **very** unfamiliar with ruby, but OK with command line debugging and generally poking around in docker containers, so I dropped into a running container but couldn't find sassc amongst the gems.

I have attempted to manually install the sassc gem using `gem install sassc` and while that seemed to complete without error it didn't solve the problem. Variations on `bundle install` also failed but I really don't know the best approach here so it's possible I didn't do this correctly.

I'd be very grateful for any assistance people can provide- step by step instructions would be really nice if there's any further debugging I can do to help resolve the issue.

Thanks in advance

Jo

**Comment by ronaldtse** [comment]
Thanks @archaeogeek for raising this issue. 

By any chance you have a "Gemfile" in the document folder? Typically a user should not need to do anything with the "sassc" gem. 

@CAMOBAP can you take a look at this?

**Comment by CAMOBAP** [comment]
Last ci looks good, @ronaldtse you are right, it's critical to check `Gemfile` here

@archaeogeek could you please share your `Gemfile`?

**Comment by archaeogeek** [comment]
Thanks for the prompt response. I should have said initially that I am following the "simple adoption" approach from https://www.metanorma.org/builder/topics/simple-adoption/ and all I have is a `metanorma.yml` file, which is based almost exactly on the default one listed:
```
metanorma_name: generic
organization_name_short: myorg
organization_name_long: My Org Name
document_namespace: https://www.metanorma.org/standards/generic
xml_root_tag: 'generic-standard'
logo_path: /config/mylogo.jpg
logo_paths: []
validate_rng_file: lib/asciidoctor/generic/generic.rng
htmlcoverpage: lib/isodoc/generic/html/html_generic_titlepage.html
htmlintropage: lib/isodoc/generic/html/html_generic_intro.html
htmlstylesheet: lib/isodoc/generic/html/htmlstyle.scss
scripts: lib/isodoc/generic/html/scripts.html
standardstylesheet: lib/isodoc/generic/html/generic.scss
header: lib/isodoc/generic/html/header.html
wordcoverpage: lib/isodoc/generic/html/word_generic_titlepage.html
wordintropage: lib/isodoc/generic/html/word_generic_intro.html
wordstylesheet: lib/isodoc/generic/html/wordstyle.scss
#i18nyaml: lib/isodoc/generic/html/i18n-en.yml
boilerplate: lib/asciidoctor/generic/boilerplate.xml
docid_template: "{{ organization_name_short }} {{ docnumeric }}"
published_stages: ["published", "withdrawn"]
committees: []
relations: []
stage_abbreviations:
  draft-proposal:
  draft-development:
  draft-testing:
  draft-implementation:
  in-force:
  retired:
metadata_extensions: []
doctypes: ['standard']
default_doctype: standard
termsdefs_titles:
  - Terms and definitions
  - Terms, definitions, symbols and abbreviated terms
  - Terms, definitions, symbols and abbreviations
  - Terms, definitions and symbls
  - Terms, definitions and abbreviations
  - Terms, definitions and abbreviated terms
symbols_titles:
  - Symbols and abbreviated terms
  - Symbols
  - Abbreviated terms
  - Abbreviations
normref_titles:
  - Normative references
bibliography_titles:
  - Bibliography
```
Then in my asciidoc file I just have `:customize: metanorma.yml` under the title.

The Simple Adoption approach with the yml file implies that's all I need- rather than attempting the ruby gem approach (this being my first attempt at metanorma and ruby)- unless I've missed something in the instructions?
