### ISSUE TITLE
Parallelize container image builds for linux/amd64 and linux/arm64

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-docker#192]
Currently, this step sequentially builds amd64 and arm64 containers:

https://github.com/metanorma/metanorma-docker/blob/70d26e3c83fa10003313eb1d241ad48feff81c5e/.github/workflows/build-push.yml#L389-L404

On Docker's documentation, they describe the ability to build on both platforms in parallel:
* https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

Basically:

Add this to the job:
```yaml
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
```

Then merge the parallel builds:
```
  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
```

This will shrink our build times.
